#!/bin/bash
# kubctl-0x02 - Apply blue/green deployments and check logs for errors.

set -e

echo "Applying Blue deployment..."
kubectl apply -f messaging_app/blue_deployment.yaml

echo "Applying Green deployment..."
kubectl apply -f messaging_app/green_deployment.yaml

echo "Applying Service..."
kubectl apply -f messaging_app/kubeservice.yaml

echo "Verifying pods..."
kubectl get pods

echo "Checking logs for Green deployment..."
GREEN_POD=$(kubectl get pods -l app=django-green -o jsonpath='{.items[0].metadata.name}')
kubectl logs $GREEN_POD

echo "✅ Blue-Green deployments applied and logs checked successfully!"
